import os
from flask import Flask, render_template, request, json
import joblib
import pandas as pd

app = Flask(__name__)

modelo = joblib.load('modelo_aluguel_rf.pkl')
preprocessor = joblib.load('preprocessor.pkl')

campo_grande = {
    "Centro": {
            "Centro": ["Centro", "Cidade", "Vila Alta", "Vila General Wolfgrand", "Vila América", "Vila Ilgenfritz", "Vila Clementina", 
                      "Jardim Aclimação", "Vila Bartiria"],
            "São Francisco": ["Vila São Francisco", "Vila Helena", "Vila Anfe", "Vila Cristina", "Vila São Sebastião", "Vila Aprazível", 
                              "Jardim Cidade", "Jardim Brasil", "Vila Alto das Paineiras", "Sanziro Katayama", "Vila São Thomé", 
                              "Vila Capri", "Vila Benjamim", "Vila Esplanada", "Vila São Luís", "Cofermat", "Vila Santa Bárbara", "Cascudo", 
                              "São Francisco"],
            "Cruzeiro": ["Cruzeiro", "Clube Campestre Ypê", "Vila Rosa", "Vila Marman", "Vila Gomes", "Vila Célia", 
                         "Coophagrande (Conjunto Eudes Costa)", "Vila Suíça", "Conjunto Residencial Monte Castelo", "Coophaban"],
            "Jardim dos Estados": ["Jardim dos Estados", "Vila Santa Odete", "Vila Guaraciaba", "Vila Tupaceretan", "Vila Esportiva", 
                                   "Vila XV de Novembro", "Jardim 7 de Setembro", "Vila Mandeta", "Vila São Jorge", "Cachoeira", "Vila Onze", 
                                   "Vila São Gabriel", "Vila Mariana", "Vila Bernardo Goldman", "Vila Isís", "Vila Abdo", 
                                   "Vila Alto Campo de Marte", "Vila Santério", "Vila da Saúde", "Vila Paulistana", "Vila Paraíso", 
                                   "Vila Paraíso Suplemento", "Vila São Elias", "Vila Lia", "Chácara dos Coqueiros", "Vila Rolim", 
                                   "Vila Suburbano", "Vila Sant’ana", "Vila Maria"],
            "Bela Vista": ["Jardim Bela Vista", "Vila Costa Lima", "Jardim Santa Catarina", "Chácara Vendas", "Jardim Nova Era", 
                           "Residencial Village", "Vila Antônio Vendas", "Vila Miguel Couto", "Jardim Alegre", "Chácara Boa Vista",
                           "Villa Di Parma"],
            "Itanhangá": ["Itanhangá Park", "Jardim Piracicaba", "Vila Gatão", "Vila Rosa Pires", "Vila Dr. João Rosa", "Vila Rezende",
                          "Jardim Vista Alegre", "Vila Joselito", "Coophamorena", "Glaucos da Costa Marques"],
            "São Bento": ["Jardim São Bento", "Vila Nova São Bento", "Jardim Guarujá", "Vila Galvão"],
            "Monte Líbano": ["Jardim Monte Líbano", "Vila Santo André", "Jardim de Allah", "Vila Antônio Inácio de Souza"],
            "Glória": ["Vila Glória", "Vila Fortuna", "Vila Eva", "Vila Oriente", "Vila Gaspar", "Vila Taveira", "Vila Sol Nascente", 
                       "Vila Ornelas", "Vila Santa Filomena", "Vila São Miguel", "Vila Castelo", "Vila Jardim Alvorada", "Vila Liberdade", 
                       "Vila Santa Dorothea"],
            "Carvalho": ["Vila Carvalho", "Vila Nossa Senhora de Lourdes", "Vila São José", "Vila Santa Maria", "Vila Quito", 
                         "Vila Carvalho Baís", "Emílio Cury", "Vila São Rafael", "Vila Oliveira", "Vila Americana", "Vila Santa Luiza"],
            "Amambaí": ["Amambaí", "Vila Perseverança", "Vila Maracajú", "Vila Guenka", "Vila São João", "Vila Santo Antônio", "Vila Olga", 
                        "Vila Barão do Rio Branco", "Vila Aurora", "Vila Warde", "Vila Floresta", "Vila Portão de Ferro", "Vila Orpheu Baís", 
                        "Vila São Vicente", "Cohasmat (Sargento Amaral)", "Vila Sargento Amaral"],
            "Cabreúva": ["Cabreúva", "Vila Esplanada", "Vila Feliciana Carolina", "Vila Santa Rosa", "Vila Marisa", "Vila Guarani", 
                         "Vila Independência"],
            "Planalto": ["Vila Planalto", "Vila Soares", "Vila Soares", "Vila São Manoel", "Vila Santa Tereza", "Vila Estephania", 
                         "Vila Alto Sumaré", "Vila Corumbá", "Vila Santos", "Vila Boa Vista", "Monte Verde", "Colinas de Campo Grande", 
                         "Sky Residence"]
            },
    "Segredo": {
        "José Abrão": ["Núcleo Habitacional José Abrão", "Parque dos Laranjais", "Jardim das Paineiras", "Vila Oeste", 
                               "Manoel Taveira", "Núcleo Parque dos Laranjais", "Jardim das Virtudes"],
        "Nasser": ["Vila Nasser", "Santa Luzia", "Vila Cox", "Jardim Alto São Francisco", "Jardim das Acácias", "Vila Lili", 
                    "Parque Residencial Azaléia", "Jardim Veneza", "Loteamento Municipal Dr. Miguel Vieira Ferreira", 
                    "Jardim Fluminense", "Nossa Senhora das Graças", "Vila Nilza", "Jardim Paquetá", "Coophasul", 
                    "Vila Nossa Senhora Aparecida", "Vila Neuza", "Vila Marli", "Vila Novo Horizonte", "Bosque da Saúde", 
                    "São Caetano", "Jardim Paradiso", "Jardim Monte Alto", "Loteamento Dona Dedé", "Setvillage I", 
                    "Setvillage II", "Água Limpa Park", "Residencial Carajás", "Morada dos Deuses", "Residencial Alto Tamandaré", 
                    "Residencial Recanto do Cerrado", "Bom Retiro", "Residencial Tolentino", "Jardim da Mooca", 
                    "Vila Nossa Senhora das Graças", "Residencial Maria Neves", "Loteamento Maria Neves"],
        "Seminário": ["Bairro Seminário", "Jardim Seminário", "Jardim Seminário II", "Vila Santa Lúcia", "Vila Jardim Maria Amélia", 
                      "Vila Nossa Senhora da Conceição", "Jardim Oracília", "Vila Dalila", "Vila Leda", "Vila Antonieta", 
                      "Vila São Roque", "Vila Saraiva", "Portal do Gramado", "São Benedito", "Lagoa da Cruz", "Vila Lídia", "North Park", 
                      "Residencial Novo Seminário"],
        "Monte Castelo": ["Monte Castelo", "Residencial Vale do Sol I", "Residencial Vale do Sol II", "Residencial Vale do Sol III", 
                          "Residencial Indaiá", "Jardim São Paulo", "Vila São João Bosco", "Residencial Otávio Pécora", 
                          "Jardim Bosque de Avilan", "Center Park", "Jardim Aruba", "Loteamento Campo Dourado", 
                          "Loteamento Costa Verde", "Praia da Urca", "Residencial Gabura"],
        "Mata do Segredo": ["Jardim das Cerejeiras", "Jardim Campo Novo", "Jardim Presidente", "Jardim Campo Belo", 
                            "Loteamento Municipal Salinas", "Loteamento Municipal Cristaldo", "Núcleo das Cerejeiras", 
                            "Jardim Nascente do Segredo", "Residencial Gama", "Arnaldino da Silva", "Treviso", "Mata do Segredo"],
        "Coronel Antonino": ["Coronel Antonino", "Estrela do Sul", "Jardim Imperial", "Jardim Mirasol", 
                             "Eldorado", "Vila Califórnia", "Vila Triângulo", "Guanabara", "Morada Verde", 
                             "Conjunto Residencial Nova Olinda", "Jardim Campo Verde", "Loteamento Municipal Raízes", 
                             "Favela Rio de Janeiro", "Favela Guatambu", "Beco da Liberdade", "Favela Nacional", 
                             "Loteamento Municipal Jaburu", "Núcleo Morada Verde", "Parque Izabel Garden’s", "Jardim Talismã", 
                             "Residencial Atlântico Sul", "Loteamento Morada do Sossego", "Jardim Barcelona", "Morada do Sossego", 
                             "Morada do Sossego II", "Recanto Pantaneiro", "Villa Ravenna", "Villa Ravenna II", "Ary Abussafi de Lima", 
                             "Gregório Correa", "Vila Ravenna", "Vila Ravenna II"],
        "Nova Lima": ["Nova Lima", "Jardim Anache", "Jardim Columbia", "Loteamento Municipal Pereira Borges", "Favela Jardim Anache", 
                      "área F", "Jardim Vida Nova", "Vida Nova II", "Tarsila do Amaral", "Vida Nova III", "José Prates", 
                      "Coriolando da Silva Correa I", "Coriolando da Silva Correa II", "José Tavares do Couto", 
                      "Oscar Salazar Moura da Cruz, Parque Iguatemi"]
    },
    "Prosa": {
        "Autonomista": ["Jardim Autonomista", "Jardim Autonomista II", "Jardim Autonomista III", "Jardim Giocondo Orsi", 
                        "Jardim Giocondo Orsi II", "Monte Carlo", "Vila Monte Carlo", "Vila Rica", "Vila Taquari", "Vila Cacique", "Vila Pagé", 
                        "Jardim Vitrine", "Vila Orsi", "Vila Cruzeiro do Sul", "Loteamento Petit Park", "Coophabanco", 
                        "Vila Boa Esperança", "Coophafé"],
        "Santa Fé": ["Santa Fé", "Vila Santos Gomes", "Conjunto Residencial Nova Ipanema", "Vivendas do Bosque", "Royal Park"],
        "Chácara Cachoeira": ["Chácara Cachoeira", "Chácara Cachoeira II", "Cachoeirinha", "Jatiúca Park", "Vila Miguel Couto", 
                              "Vila Manoel da Costa Lima", "Jardim Umuarama", "Cidade Jardim", "San Marino Park", "Nahima Park", 
                              "Altos da Afonso Pena", "Parque dos Poderes"],
        "Carandá": ["Carandá Bosque", "Carandá Bosque II", "Carandá Bosque III", "Golden Gate Park", "Portal Itayara", "Vila do Polonês", 
                    "Tayamã Park", "Vila Nascente", "Loteamento Copacabana", "Loteamento Municipal Mário de Andrade", "Residencial Itacolomi", 
                    "Tropical Park", "Loteamento Residencial Via Park", "Residencial Via Park Itália"],
        "Margarida": ["Vila Margarida", "Vila Lucinda", "Vila Catarina", "Vila Catarina II", "Vila Carolina", "Jardim Marabá", 
                      "Loteamento Municipal Joaquim Euzébio", "Loteamento Municipal Guaicurus", "Loteamento Municipal Verde Brasil", 
                      "Núcleo Marabá", "Loteamento Municipal Paulo VI"],
        "Mata do Jacinto": ["Mata do Jacinto", "Conjunto Mata do Jacinto", "Favela do Limão", "Loteamento Municipal Ceasa", 
                            "Loteamento Municipal Nazaré", "Loteamento Abaeté", "Loteamento Sóter", "Residencial Sóter"],
        "Novos Estados": ["Parque dos Novos Estados", "Jardim Montevidéu", "Conjunto Residencial Novo Amazonas",
                          "Conjunto Residencial Nova Bahia", "Nova Bahia", "Conjunto Residencial Novo Pernambuco", 
                          "Conjunto Residencial Novo Rio Grande do Sul", "Conjunto Residencial Novo Maranhão", 
                          "Conjunto Residencial Novo Sergipe", "Conjunto Residencial Novo São Paulo", 
                          "Conjunto Residencial Novo Alagoas", "Conjunto Residencial Novo Minas Gerais", 
                          "Conjunto Residencial Novo Paraná", "Jardim Jacarandá", "Alphaville Campo Grande", 
                          "Alphaville Campo Grande II", "Alphaville Campo Grande III", "Alphaville Campo Grande IV", 
                          "Terras Alpha Campo Grande"],
        "Estrela Dalva": ["Jardim Estrela Dalva", "Jardim Estrela Dalva I, Jardim Estrela Dalva II, Jardim Estrela Dalva III, Taquaral Bosque"],
        "Veraneio": ["Jardim Veraneio", "Vila Futurista", "Vila Danúbio Azul", "Jardim Tayana", "Vila Abdalla", "Desbarrancado", 
                     "Jardim Arco-Íris", "Loteamento Bosque da Esperança", "Beirute Residence Park", "Bosque da Esperança II"],
        "Chácara dos Poderes": ["Chácara dos Poderes", "Jardim Pinheiros", "Jardim Cabral", "Vila Telma", "Vila Raquel", "Vila Sônia"],
        "Noroeste": ["Jardim Noroeste", "Loteamento Nova Serrana", "Serraville", "Residencial Shalom"]
    },
    "Bandeira": {
        "Jardim Paulista": ["Jardim Paulista", "Vila Progresso", "Paranaense"],
        "TV Morena": ["Jardim TV Morena"],
        "Vilasboas": ["Vila Vilasboas", "Vila Vilas Boas", "Jardim Alegre", "Vila Portinho Frederico Pache", "Indiana Park", 
                      "Jardim Mansur", "Jardim Auxiliadora", "Jardim Ipanema", "Parque Dallas", "Residencial Vila Olímpica", 
                      "Villas Park Residence", "Amantini Residence"],
        "São Lourenço": ["Jardim São Lourenço", "Jardim Ibirapuera", "Vila Almeida Lima", "Vila Zoe"],
        "Tiradentes": ["Tiradentes", "Residencial Nova Tiradentes", "Jardim Flamboyant", "Jardim Flamboyant II", 
                       "Parque Residencial Arnaldo Estevão de Figueiredo", "Parque Residencial Arnaldo Estevão de Figueiredo II", 
                       "Loteamento Municipal Dalva de Oliveira", "Loteamento Municipal Dalva de Oliveira II", "Loteamento Municipal Cavan", 
                       "Núcleo Tiradentes", "Regina", "Residencial Itatiaia", "Vila Jardim São Bernardo", "Jardim Vitória", 
                       "Parque Residencial Anhembi", "Loteamento Portobello", "Loteamento Marçal de Souza", "Jardim Cristo Redentor", 
                       "Loteamento Estrela Parque", "Jardim São Judas Tadeu", "Jardim Jerusalém", "Jardim Itatiaia"],
        "Maria Aparecida Pedrossian": ["Parque Residencial Maria Aparecida Pedrossian", "Panorama", "Vivendas do Parque", 
                                       "Jardim Samambaia", "Residencial Oiti", "Núcleo Panorama", 
                                       "Parque Residencial Damha", "Parque Residencial Damha II", "Parque Residencial Damha III",
                                       "Parque Residencial Damha IV", "Residencial Damha", "Residencial Damha II", "Residencial Damha III",
                                       "Residencial Damha IV"],
        "Rita Vieira": ["Parque Residencial Rita Vieira", "Parque Rita Vieira", "Vila Dom Pedrito", "Vila Morumbi", "Coopharádio", 
                        "Chácara José Antônio Pereira", "Jardim Lagoa Dourada", "Jardim Nossa Senhora do Perpétuo Socorro", "Jardim Itamaracá", 
                        "Jardim Anhanguera", "Jardim Águas Vivas"],
        "Carlota": ["Vila Carlota", "Vila Ieda", "Jardim Itapema"],
        "Dr. Albuquerque": ["Vila Dr. Albuquerque", "Vila Albuquerque", "Vila Olinda", "Vila Maciel"],
        "Universitário": ["Universitário", "Residencial Betaville", "Vila Concórdia", "Vila Santo Eugênio", "Jardim Ametista", 
                          "Jardim Tropical", "Pequena Flor I", "Jardim das Perdizes", "Recanto das Palmeiras", "Jardim Campo Limpo", 
                          "Núcleo Habitacional Recanto dos Rouxinóis", "Jardim Moema", "Sitiocas Alvorada", "Jardim Campina Verde", 
                          "Jardim Campo Alto", "Jardim Pacaembu", "Núcleo Campina Verde", "Jardim Indianápolis", "Vila Julieta", 
                          "Jardim Antares", "Edson Brito Garcia", "Loteamento Volpe", "Loteamento Volpe II"],
        "Moreninha": ["Núcleo Habitacional Moreninha I", "Núcleo Habitacional Moreninha II", "Núcleo Habitacional Moreninha III", 
                      "Loteamento Moreninha IV", "Chácara Novo Horizonte", "Jardim Santa Felicidade", "Vila Cidade Morena", 
                      "Loteamento Municipal Ribeira", "Jardim Gramado", "Jardim Nova Capital", "Jardim Nova Jerusalém", 
                      "Jardim do Córrego", "Residencial Terra dos Pequis", "Paraíso do Lageado", "Vila Moreninha", "Vila Moreninha II"]
    },
    "Anhanduizinho": {
        "Taquarussu": ["Jardim Taquarussu", "Cohafama", "Vila Santo Afonso", "Vila Afonso Pena", "Vila Afonso Pena Júnior", "Vila Itamarati"],
        "Joquey Club": ["Vila Jardim Jockey Club", "Vila Marcos Roberto", "Vila Bom Jesus", "Vila Santa Amélia Baís", 
                        "Residencial Santa Celina", "Jardim Jockey Club"],
        "América": ["Jardim América", "Vila Jardim América", "Vila Valparaíso"],
        "Piratininga": ["Vila Piratininga", "Jardim Nhanhá", "Promorar", "Vila Ipiranga", "Núcleo Piratininga", "Vila Getúlia Barbosa", 
                        "Vitta Bella"],
        "Jacy": ["Jardim Jacy", "Vila Nova Bandeirantes"],
        "Guanandi": ["Guanandi", "Favela Dona Neta", "Favela Núcleo Guanandi I"],
        "Aero Rancho": ["Aero Rancho", "Núcleo Habitacional Aero Rancho", "Núcleo Habitacional Aero Rancho II", 
                        "Núcleo Habitacional Aero Rancho III", "Núcleo Habitacional Aero Rancho IV", "Núcleo Habitacional Aero Rancho V", 
                        "Jardim das Hortênsias"],
        "Parati": ["Jardim Parati", "Jardim Parati II", "Granja Bandeira", "Loteamento Alto da Boa Vista", "Jardim das Nações", 
                   "Conjunto Parati", "Conjunto Parati II"],
        "Pioneiros": ["Pioneiros", "Jardim Colonial", "Residencial do Lago", "Vila Adelina", "Vila Jardim Pioneiros", "Vila Santa Branca", 
                      "Jardim Santa Úrsula", "Recanto das Andorinhas", "Jardim das Mansões", "Universitárias", 
                      "Conjunto Habitacional Jardim Anápolis", "Jardim Rubiácea", "Jardim Jane", "Jardim Botafogo", "Jardim Morenão", 
                      "Jardim Vicentino", "Jardim Roselândia", "Residencial Botafogo", "Parque Residencial Lisboas", "Jardim Botânico", 
                      "Jardim Botânico II", "Jardim Agulhas Negras", "Porto Galo", "Residencial Geraldo Correa da Silva"],
        "Alves Pereira": ["Vila Alves Pereira", "Universitário Seção D", "Jardim Monumento", "Vila Antunes", "Parque do Trabalhador", 
                          "Residencial João Scarano", "Jardim Colibrí", "Jardim Colibri", "Jardim Colibri II", 
                          "Núcleo Habitacional Universitárias I", "Núcleo Habitacional Universitárias II", "Jardim Macapá", 
                          "Loteamento Municipal Alan Soares", "Núcleo Colibri II", "Núcleo Alves Pereira", "Jardim Nashville", 
                          "Vila Clélia", "Loteamento Porto Seguro", "Residencial Ilhéus", "Cidade Nova"],
        "Centenário": ["Jardim Centenário", "Jardim Monte Alegre", "Carlinda Pereira Contar", "Vila Nogueira", "Vila Amapá", "Vila Aimoré", 
                       "Vila Aimoré II", "Parque Residencial Iracy Coelho Netto", "Parque Residencial Iracy Coelho Netto II", 
                       "Parque Residencial Iracy Coelho Netto III", "Núcleo Centenário", "Núcleo Vila Nogueira", "Jardim Pênfigo", 
                       "Residencial Vila Bela", "Residencial Ouro Preto", "Jardim Manaíra", "Jardim Monterey", "Jardim Radialista", 
                       "Loteamento Residencial Cedrinho", "Jardim das Princesas I", "Jardim das Princesas II", "Vila Áurea"],
        "Lageado": ["Parque do Lageado", "Loteamento Municipal Dom Antônio Barbosa", "Parque do Sol", "Jardim Colorado", 
                    "Residencial José Teruel Filho", "Parque dos Sabiás"],
        "Los Angeles": ["Los Angeles", "Jardim Los Angeles", "Jardim Sumatra", "Jardim Morada do Sol", "Jardim Uirapuru", 
                        "Loteamento Vespasiano Martins", "Residencial Terra Morena"],
        "Centro-Oeste": ["Jardim Centro Oeste", "Jardim Marajoara", "Jardim Bálsamo", "Jardim Campo Nobre", "Jardim das Macaúbas", 
                         "Jardim das Meninas", "Loteamento Municipal Brandão", "Núcleo Jardim das Macaúbas", "Jardim Canguru", 
                         "Jardim Paulo Coelho Machado", "Parque Novo Século", "Jardim Mário Covas", "Varandas do Campo"]
    },
    "Lagoa": {
        "Taveirópolis": ["Vila Taveirópolis", "Santos Dumont", "Vila Belo Horizonte"],
        "Bandeirantes": ["Vila Bandeirantes", "Coophavila", "Desmembramento Cornelas", "Vila Jurema", "Vila Bandeirante"],
        "Caiçara": ["Caiçara", "Vila dos Marimbas", "Vila Jardim Anahy", "Vila Maringá"],
        "União": ["União", "Parque Residencial União", "Parque Residencial União II", "Residencial Oliveira", "Residencial Oliveira I", 
                  "Residencial Oliveira II", "Residencial Oliveira III", "Residencial das Flores", "Parque Residencial dos Girassóis"],
        "Leblon": ["Jardim Leblon", "Vila Jussara", "Conjunto Habitacional Bonança", "Jardim Europa", "Coophamat", "Jardim da Lapa", 
                   "Desmembramento Flório Alcebíades Brandão", "Jardim Antarctica", "Vila Ouro Fino", "Jardim Tatiana", 
                   "Vila Ospampas", "Loteamento Bonjardim", "Núcleo Habitacional Buriti", "Alto Leblon", "Jardim Bonança", "Vila Flório"],
        "São Conrado": ["Jardim São Conrado", "Jardim Santa Emília", "Loteamento Municipal Interpraia", "Vila Major Juares", 
                        "Residencial Aquárius I", "Residencial Aquárius II", "Residencial Figueiras do Parque"],
        "Tijuca": ["Jardim Tijuca", "Jardim Tijuca II", "Jardim dos Boggi", "Vila Vilma", "São Pedro", "Jardim Verdes Mares", 
                   "Residencial Barra da Tijuca", "Residencial Barra da Tijuca II"],
        "Caiobá": ["Portal Caiobá", "Portal Caiobá II", "Rancho Alegre II", "Vila Fernanda", "Rivieira Park", "Jardim Rancho Alegre I", 
                   "Bela Laguna", "Loteamento Bela Laguna", "Loteamento Rancho Alegre", "Loteamento Rancho Alegre II"],
        "Batistão": ["Jardim Batistão", "São Jorge da Lagoa", "Jardim Mato Grosso", "Conjunto Residencial Serra Azul", "Lagoa Park", 
                     "Jardim Villa Lobos", "Jardim Villa Lobos II"],
        "Coophavila II": ["Coophavila II", "Jardim Vila Kellem", "Jardim Ouro Verde", "Favela Tarumã"],
        "Tarumã": ["Jardim Tarumã", "Conjunto Residencial Tarumã", "Portal das Laranjeiras", "Jardim Sol Poente", "Jardim Corcovado", 
                   "Vila Jandaia", "Arapongas"]
    },
    "Imbirussu": {
        "Sobrinho": ["Vila Sobrinho", "Vila Acrópolis", "Vila Santa Rita", "Vila Rosalina", "Vila Nossa Senhora Auxiliadora", "Cophaco", 
                     "Parque dos Ipês", "Jardim Leonidia", "Coopermat", "Vila Alba", "Vila Espanhola", "Jardim Ipanema", 
                     "Vila Duque de Caxias", "Vila Cinamomo", "Lar do Trabalhador", "Residencial Parque dos Flamingos", "Vila Aviação", 
                     "Parque São Domingos", "Vila Oeste", "Loteamento Papa João Paulo II", "Sobrinho"],
        "Santo Amaro": ["Vila Santo Amaro", "Vila Jardim Beija-Flor", "Parque dos Laranjais", "Manoel Taveira", "Santa Carmélia", 
                        "Jardim Itapuã", "Coophatrabalho", "Vila Dr. Jair Garcia", "Jardim Canadá", "Vila São Marcos", "Vila Almeida", 
                        "Vila Palmira", "Jardim Mandala", "Residencial Sírio Libanês I", "Residencial Sírio Libanês II", 
                        "Jardim das Virtudes", "Residencial Hugo Rodrigues"],
        "Santo Antônio": ["Santo Antônio", "Jardim Imá", "Vila Nova", "Loteamento Municipal Jaguaribe", "Vila Doriza", 
                          "Jardim Petrópolis", "Vila Bosque da Saudade", "Vila Coutinho", "Vila Sílvia Regina"],
        "Panamá": ["Jardim Panamá", "Jardim Panamá II", "Jardim Panamá III", "Jardim Panamá IV", "Jardim Panamá V", "Jardim Panamá VI", 
                   "Parque Residencial dos Bancários", "Residencial Sagarana", "Jardim Aroeira", "Recanto dos Pássaros", 
                   "Jardim do Zé Pereira", "Residencial Ana Maria do Couto", "Parque Residencial Bellinate", "Residencial Búzios",
                   "Portal do Panamá", "Jardim Mathilde", "Bosque das Araras", "Panamá"],
        "Popular": ["Jardim das Reginas", "Loteamento Municipal Macaé", "Jardim Sayonara", "Jardim Pantanal", "Santa Mônica", 
                    "Jardim Aeroporto", "Jardim Itália", "Bosque Santa Mônica", "Bosque Santa Mônica II", "Vila Romana"],
        "Nova Campo Grande": ["Nova Campo Grande", "Vila Eliane", "Vila Serradinho", "Jardim Carioca", "Residencial Nelson Trad", 
                              "Vila Nova Campo Grande"],
        "Núcleo Industrial": ["Núcleo Industrial", "Jardim Inápolis", "Vila Manoel Secco Thomé", "Vila Entroncamento", 
                              "Pólo Empresarial Oeste", "Morada Imperial"]
    }
}


@app.route("/", methods=['GET', 'POST'])
def estimador():
    valor_predito = None
    dados_form = {}
    
    if request.method == 'POST':
        dados_form = {
            'tipo': request.form['tipo'],
            'regiao': request.form['regiao'],
            'bairro': request.form['bairro'],
            'localizacao': request.form['localizacao'],
            'area': float(request.form['area']),
            'quarto': int(request.form['quarto']),
            'banheiro': int(request.form['banheiro']),
            'vagas_garagem': float(request.form['vagas_garagem']),
            'eh_condo': int(request.form['eh_condo'])
        }

        df = pd.DataFrame([dados_form])
        valor_predito = modelo.predict(df)[0]

    return render_template('estimador.html', valor_predito=valor_predito, campo_grande=campo_grande, **dados_form)

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 10000))
    app.run(host='0.0.0.0', port=port)